server:
  port: 9191

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrdb?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@12345
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

