spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment-db
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@12345
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
