spring:
  datasource:
    url: jdbc:tc:postgresql:9.6.8:///testdb
    username: postgres
    password: admin
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    show-sql: true
  flyway:
    enabled: false