spring:
  datasource:
    url: jdbc:tc:postgresql:16.2:///testdb
    username: postgres
    password: admin
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    defer-datasource-initialization: false
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:tc:postgresql:16.2:///testdb
